[project]
name = "goku"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">3.9,<3.12"
dependencies = [
    "gym",
    "matplotlib",
    "numpy>1.8.0,<2.0.0",
    "pip",
    "pygame>=2.6.1",
    "scikit-image",
    "scipy",
    "torch",
    "tqdm",
    "wheel<0.40.0",
]
